package cityGarbageCollector.gui;

import jadex.bridge.service.types.cms.CreationInfo;

import java.util.HashMap;
import java.util.Map;

import javax.swing.JOptionPane;
import javax.swing.JPanel;

import cityGarbageCollector.GCollector;
import cityGarbageCollector.Location;
import cityGarbageCollector.agent.CollectorBDI;
import cityGarbageCollector.agent.CollectorBDI.Trash_Type;

public class AgentOptions extends JPanel {

	public AgentOptions() {
		// TODO Auto-generated constructor stub
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		tf_agent_name = new javax.swing.JTextField();
		jLabel2 = new javax.swing.JLabel();
		tf_agent_x = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		tf_agent_y = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		cb_agent_type = new javax.swing.JComboBox();
		jLabel5 = new javax.swing.JLabel();
		tf_agent_cap = new javax.swing.JTextField();
		bt_agent_deploy = new javax.swing.JButton();

		setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

		jLabel1.setText("Name:");
		add(jLabel1);

		tf_agent_name.setMaximumSize(new java.awt.Dimension(60, 24));
		tf_agent_name.setMinimumSize(new java.awt.Dimension(60, 24));
		tf_agent_name.setPreferredSize(new java.awt.Dimension(60, 24));
		add(tf_agent_name);

		jLabel2.setText("x:");
		add(jLabel2);

		tf_agent_x.setMaximumSize(new java.awt.Dimension(28, 24));
		tf_agent_x.setMinimumSize(new java.awt.Dimension(28, 24));
		tf_agent_x.setPreferredSize(new java.awt.Dimension(28, 24));
		add(tf_agent_x);

		jLabel3.setText("y:");
		add(jLabel3);

		tf_agent_y.setMaximumSize(new java.awt.Dimension(28, 24));
		tf_agent_y.setMinimumSize(new java.awt.Dimension(28, 24));
		tf_agent_y.setPreferredSize(new java.awt.Dimension(28, 24));
		add(tf_agent_y);

		jLabel4.setText("Type:");
		add(jLabel4);

		cb_agent_type.setModel(new javax.swing.DefaultComboBoxModel(Trash_Type.values()));
		add(cb_agent_type);

		jLabel5.setText("Capacity:");
		add(jLabel5);

		tf_agent_cap.setMaximumSize(new java.awt.Dimension(30, 24));
		tf_agent_cap.setMinimumSize(new java.awt.Dimension(30, 24));
		tf_agent_cap.setPreferredSize(new java.awt.Dimension(30, 24));
		add(tf_agent_cap);

		bt_agent_deploy.setText("Deploy");
		bt_agent_deploy.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				bt_agent_deployActionPerformed(evt);
			}
		});
		add(bt_agent_deploy);
	}// </editor-fold>

	public void setAgentLocation(int x, int y) {
		this.tf_agent_x.setText("" + x);
		this.tf_agent_y.setText("" + y);
	}

	// ================================================================================
	// Actions && Listeners
	// ================================================================================

	private void bt_agent_deployActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		// Deploy button action goes here
		String name = tf_agent_name.getText();
		int cap = -1, x = -1, y = -1;
		try {
			x = Integer.parseInt(tf_agent_x.getText());
			y = Integer.parseInt(tf_agent_y.getText());
			cap = Integer.parseInt(tf_agent_cap.getText());
		} catch (NumberFormatException ex) {
			System.err.println("Some values could not be parsed.");
		}
		Location loc = new Location(x, y);
		if (GCollector.getInstance().isRoadOnLocation(loc)) {
			Trash_Type type = (Trash_Type) cb_agent_type.getSelectedItem();
			Map<String, Object> agentArgs = new HashMap<String, Object>();
			agentArgs.put("Location", loc);
			if (cap != -1)
				agentArgs.put("Capacity", cap);
			if (name.length() > 0)
				agentArgs.put("Name", name);
			agentArgs.put("Type", type);
			CreationInfo cInfo = new CreationInfo(agentArgs);
			GCollector.getInstance().launchAgent(CollectorBDI.CLASS_PATH, cInfo);
		} else {
			JOptionPane.showMessageDialog(this, "Please insert agent on a Road.", "Bad location", JOptionPane.ERROR_MESSAGE);
		}
	}

	// Variables declaration - do not modify
	private javax.swing.JButton bt_agent_deploy;
	private javax.swing.JComboBox cb_agent_type;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JTextField tf_agent_cap;
	private javax.swing.JTextField tf_agent_name;
	private javax.swing.JTextField tf_agent_x;
	private javax.swing.JTextField tf_agent_y;
	// End of variables declaration
}
