package cityGarbageCollector.gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;

import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.KeyStroke;

import cityGarbageCollector.GCollector;

public class GlobalOptions extends JPanel {

	public GlobalOptions() {
		// TODO Auto-generated constructor stub
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {
		java.awt.GridBagConstraints gridBagConstraints;

		pn_global_top = new javax.swing.JPanel();
		cb_comunication = new javax.swing.JCheckBox();
		cb_pause = new javax.swing.JCheckBox();
		pn_speed_panel = new javax.swing.JPanel();
		jLabel6 = new javax.swing.JLabel();
		jPanel6 = new javax.swing.JPanel();
		cb_global_speed = new javax.swing.JComboBox();
		pn_global_bottom = new javax.swing.JPanel();
		jPanel1 = new javax.swing.JPanel();
		jLabel7 = new javax.swing.JLabel();
		tf_modify_map_x = new javax.swing.JTextField();
		jLabel8 = new javax.swing.JLabel();
		tf_modify_map_y = new javax.swing.JTextField();
		jPanel2 = new javax.swing.JPanel();
		jPanel5 = new javax.swing.JPanel();
		cb_modify = new javax.swing.JComboBox();
		jPanel3 = new javax.swing.JPanel();
		bt_global_modify = new javax.swing.JButton();

		setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
		setLayout(new java.awt.GridLayout(2, 1));

		pn_global_top.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Global", javax.swing.border.TitledBorder.CENTER,
				javax.swing.border.TitledBorder.DEFAULT_POSITION));
		pn_global_top.setMinimumSize(new java.awt.Dimension(160, 160));
		pn_global_top.setLayout(new java.awt.GridLayout(3, 1));

		cb_comunication.setSelected(true);
		cb_comunication.setText("Comunication");

		pn_global_top.add(cb_comunication);

		cb_pause.setText("Pause");
		pn_global_top.add(cb_pause);

		pn_speed_panel.setLayout(new java.awt.GridLayout());

		jLabel6.setText("Speed");
		pn_speed_panel.add(jLabel6);

		jPanel6.setLayout(new java.awt.GridBagLayout());

		cb_global_speed.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		gridBagConstraints = new java.awt.GridBagConstraints();
		gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
		jPanel6.add(cb_global_speed, gridBagConstraints);

		pn_speed_panel.add(jPanel6);

		pn_global_top.add(pn_speed_panel);

		add(pn_global_top);

		pn_global_bottom.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modify", javax.swing.border.TitledBorder.CENTER,
				javax.swing.border.TitledBorder.DEFAULT_POSITION));
		pn_global_bottom.setMinimumSize(new java.awt.Dimension(160, 160));
		pn_global_bottom.setLayout(new java.awt.GridLayout(2, 1));

		java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
		flowLayout1.setAlignOnBaseline(true);
		jPanel1.setLayout(flowLayout1);

		jLabel7.setText("x:");
		jPanel1.add(jLabel7);

		tf_modify_map_x.setMaximumSize(new java.awt.Dimension(28, 24));
		tf_modify_map_x.setMinimumSize(new java.awt.Dimension(28, 24));
		tf_modify_map_x.setPreferredSize(new java.awt.Dimension(28, 24));

		jPanel1.add(tf_modify_map_x);

		jLabel8.setText("y:");
		jPanel1.add(jLabel8);

		tf_modify_map_y.setMaximumSize(new java.awt.Dimension(28, 24));
		tf_modify_map_y.setMinimumSize(new java.awt.Dimension(28, 24));
		tf_modify_map_y.setPreferredSize(new java.awt.Dimension(28, 24));

		jPanel1.add(tf_modify_map_y);

		pn_global_bottom.add(jPanel1);

		jPanel2.setLayout(new java.awt.GridLayout(1, 2));

		cb_modify.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
		jPanel5.add(cb_modify);

		jPanel2.add(jPanel5);

		bt_global_modify.setText("Set");
		jPanel3.add(bt_global_modify);

		jPanel2.add(jPanel3);

		pn_global_bottom.add(jPanel2);

		add(pn_global_bottom);

		@SuppressWarnings("rawtypes")
		DefaultComboBoxModel model = new DefaultComboBoxModel(GCollector.SPEED.values());
		cb_global_speed.setModel(model);

		pauseListener = pauseAction();
		cb_pause.addActionListener(pauseListener);
		
		speedListener = changeSpeedAction();
		cb_global_speed.addActionListener(speedListener);

		modMapBtListener = mapModifyButtonClickAction();
		this.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(KeyStroke.getKeyStroke(KeyEvent.VK_S, 0),
				"paintAction");
		this.getActionMap().put("paintAction", modifyMapAction);

		// bt_global_modify.setMnemonic(KeyEvent.VK_S);
		bt_global_modify.addActionListener(modMapBtListener);

	}// </editor-fold>

	// public void doMapModBtClick(){
	// bt_global_modify.doClick();
	// }

	public void setModifyLocation(int x, int y) {
		// TODO Auto-generated method stub
		tf_modify_map_x.setText("" + x);
		tf_modify_map_y.setText("" + y);
	}

	// ================================================================================
	// Actions && Listeners
	// ================================================================================

	private ActionListener mapModifyButtonClickAction() {
		// TODO Auto-generated method stub
		return new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("Still unimplemented");
			}
		};
	}

	private ActionListener changeSpeedAction() {
		// TODO Auto-generated method stub
		return new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				GCollector.SPEED speed = (GCollector.SPEED) cb_global_speed.getSelectedItem();
				GCollector.getInstance().setSpeed(speed);
			}
		};
	}
	
	private ActionListener pauseAction() {
		// TODO Auto-generated method stub
		return new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				GCollector.getInstance().toggleAgentPause();
			}
		};
	}

	private Action modifyMapAction = new AbstractAction() {
		@Override
		public void actionPerformed(ActionEvent ae) {
			bt_global_modify.doClick();
		}
	};

	// ================================================================================
	// Variables
	// ================================================================================

	private javax.swing.JButton bt_global_modify;
	private javax.swing.JCheckBox cb_comunication;
	private javax.swing.JComboBox cb_global_speed;
	private javax.swing.JComboBox cb_modify;
	private javax.swing.JCheckBox cb_pause;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JPanel jPanel6;
	private javax.swing.JPanel pn_global_bottom;
	private javax.swing.JPanel pn_global_top;
	private javax.swing.JPanel pn_speed_panel;
	private javax.swing.JTextField tf_modify_map_x;
	private javax.swing.JTextField tf_modify_map_y;
	private java.awt.event.ActionListener speedListener;
	private java.awt.event.ActionListener modMapBtListener;
	private javax.swing.AbstractAction buttonPressed;
	private java.awt.event.ActionListener pauseListener;
	// End of variables declaration

}
